#!/usr/bin/ksh -e

tor_address() {
	find tor_hostnames/$1 -type f -print0 |grep -FzZ "$2/hostname" |xargs -0 cat
}

. env/bin/activate
export ANSIBLE_HOSTS=./hosts
ansible-playbook -vv ./main.yml $@

set -A hostnames $(ls tor_hostnames)

echo "You can reach your services at:"
{
	echo "hostname baikal ssh"
	for host in ${hostnames[*]}; do
		baikal="$(tor_address $host baikal |sed 's;$;/admin;')"
		ssh="$(tor_address $host ssh)"
		echo "${host} ${baikal} ${ssh}"
	done
} |column -t
